import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';

// POST /api/leagues
// Creates a new league + adds commissioner as first member
export async function POST(req: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies });

  // Auth check
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await req.json();
  const { name, buy_in, league_size, draft_type, salary_cap, team_name } = body;

  // Validate
  if (!name?.trim() || name.trim().length < 3) {
    return NextResponse.json({ error: 'League name must be at least 3 characters.' }, { status: 400 });
  }
  if (![4, 6, 8, 10, 12].includes(league_size)) {
    return NextResponse.json({ error: 'Invalid league size.' }, { status: 400 });
  }
  if (![0, 10, 25, 50].includes(buy_in)) {
    return NextResponse.json({ error: 'Invalid buy-in amount.' }, { status: 400 });
  }

  // Create league (invite_code generated by DB trigger)
  const { data: league, error: leagueErr } = await supabase
    .from('leagues')
    .insert({
      name:            name.trim(),
      commissioner_id: user.id,
      buy_in,
      league_size,
      draft_type:      draft_type || 'snake',
      salary_cap:      salary_cap || 200,
      invite_code:     '',  // trigger fills this
      status:          'forming',
    })
    .select('id, invite_code, name')
    .single();

  if (leagueErr || !league) {
    console.error('[API] Create league error:', leagueErr);
    return NextResponse.json({ error: leagueErr?.message || 'Failed to create league.' }, { status: 500 });
  }

  // Add commissioner as member
  const { error: memberErr } = await supabase
    .from('league_members')
    .insert({
      league_id:  league.id,
      user_id:    user.id,
      team_name:  team_name?.trim() || 'Team 1',
      draft_slot: 1,
      paid:       buy_in === 0,  // auto-mark paid for free leagues
    });

  if (memberErr) {
    console.error('[API] Add commissioner member error:', memberErr);
    // League created but membership failed — non-fatal, still return success
  }

  return NextResponse.json({ data: league, error: null }, { status: 201 });
}

// GET /api/leagues
// Returns all leagues the current user is a member of
export async function GET(_req: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies });

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data, error } = await supabase
    .from('league_members')
    .select(`
      league_id,
      team_name,
      paid,
      leagues (
        id, name, status, league_size, buy_in,
        draft_type, invite_code, created_at, commissioner_id
      )
    `)
    .eq('user_id', user.id)
    .order('joined_at', { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ data, error: null });
}
